//<editor-fold defaultstate="collapsed" desc="Jibberish">
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Calculations.Convert;
import connections.MySQL;
import exceptions.UnsupportedType;
import forminterface.ParentFormInterface;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import taskplanner.Task;
//</editor-fold>

/**
 *
 * @author jeroen
 */
public class AddTaskPanel extends javax.swing.JPanel {

    //<editor-fold defaultstate="collapsed" desc="Declarations">
    MySQL connectionSettings;
    ParentFormInterface parent;

    public void setParent(ParentFormInterface parent) {
        this.parent = parent;
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Constructor">
    /**
     * Creates new form QuickAdd
     */
    public AddTaskPanel() {
        initComponents();
    }
    //</editor-fold>

    //<editor-fold desc="Methodes">
    //<editor-fold defaultstate="collapsed" desc="Initialize">
    public void Initialize(MySQL connectionSettings, ParentFormInterface parent) {
        setParent(parent);
        if (connectionSettings != null) {
            this.connectionSettings = connectionSettings;
            ArrayList<String> columns = new ArrayList<>();
            columns.add("TaskTypeName");
            ArrayList<Object> parameters = new ArrayList<>();
            ArrayList<String[]> SQLReturn = new ArrayList<>();
            try {
                SQLReturn = connectionSettings.executeSQL("SELECT * FROM TaskType", columns, parameters);
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedType ex) {
                Logger.getLogger(AddTaskPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            jComboBoxTaskType.removeAllItems();
            for (String[] entry : SQLReturn) {
                jComboBoxTaskType.addItem(entry[0]);
            }
            jComboBoxTaskType.setSelectedIndex(0);
            setFieldsVisibility();
        }
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Set Fields Visible">
    private void setFieldsVisibility() {
        switch (jComboBoxTaskType.getSelectedItem().toString()) {
            case "[SELECT]":
                jLabelToDoBefore.setVisible(false);
                jFormattedTextFieldToDoBefore.setVisible(false);
                jLabelPriority.setVisible(false);
                jSliderPriority.setVisible(false);
                break;
            case "ToDo":
                jLabelToDoBefore.setVisible(true);
                jFormattedTextFieldToDoBefore.setVisible(true);
                jLabelPriority.setVisible(true);
                jSliderPriority.setVisible(true);
        }
    }
    //</editor-fold>
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Generated Code">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdd = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jComboBoxTaskType = new javax.swing.JComboBox();
        jFormattedTextFieldToDoBefore = new javax.swing.JFormattedTextField();
        jLabelToDoBefore = new javax.swing.JLabel();
        jSliderPriority = new javax.swing.JSlider();
        jLabelPriority = new javax.swing.JLabel();
        jLabelWithDesign = new javax.swing.JLabel();

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabelName.setText("Name");

        jComboBoxTaskType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTaskTypeItemStateChanged(evt);
            }
        });

        jFormattedTextFieldToDoBefore.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yy/M/d"))));
        jFormattedTextFieldToDoBefore.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldToDoBeforeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldToDoBeforeFocusLost(evt);
            }
        });

        jLabelToDoBefore.setText("To Do Before");

        jSliderPriority.setMaximum(5);
        jSliderPriority.setMinimum(1);
        jSliderPriority.setValue(3);

        jLabelPriority.setText("Priority");

        jLabelWithDesign.setText("______________________________________________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWithDesign)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addComponent(jLabelToDoBefore)
                            .addComponent(jLabelPriority))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldToDoBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxTaskType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSliderPriority, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelWithDesign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelToDoBefore)
                                .addGap(32, 32, 32))
                            .addComponent(jLabelPriority)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxTaskType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldToDoBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    //</editor-fold>

    //<editor-fold desc="Events">
    //<editor-fold defaultstate="collapsed" desc="ComboBox Item Changed">
    private void jComboBoxTaskTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTaskTypeItemStateChanged
        jFormattedTextFieldToDoBefore.setText(Convert.toString(new Date()));
        if (jComboBoxTaskType.getSelectedItem() != null) {
            setFieldsVisibility();
        }
    }//GEN-LAST:event_jComboBoxTaskTypeItemStateChanged
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="AddButton Action">
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String name = jTextFieldName.getText();
        Date beforeDate = null;
        try {
            beforeDate = Convert.toDate(jFormattedTextFieldToDoBefore.getText());
        } catch (ParseException ex) {
            Logger.getLogger(AddTaskPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        int priority = jSliderPriority.getValue();
        Task t = new Task(name, beforeDate, priority);
        t.Save(connectionSettings);
        jTextFieldName.setText("");
        jSliderPriority.setValue(3);
        ArrayList<Object> args = new ArrayList<>();
        args.add(t);
        parent.UpdateForm("AddTask", args);
    }//GEN-LAST:event_jButtonAddActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="BeforeDate TextField Focus Gained">
    private void jFormattedTextFieldToDoBeforeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldToDoBeforeFocusGained
        jFormattedTextFieldToDoBefore.setText("");
    }//GEN-LAST:event_jFormattedTextFieldToDoBeforeFocusGained
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="BeforeDate TextField Focus Lost">
    private void jFormattedTextFieldToDoBeforeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldToDoBeforeFocusLost
        // TODO add your handling code here:
        if (jFormattedTextFieldToDoBefore.getText().equals("")) {
            jFormattedTextFieldToDoBefore.setText(Convert.toString(new Date()));
        }
    }//GEN-LAST:event_jFormattedTextFieldToDoBeforeFocusLost
    //</editor-fold>
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Generated Code">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JComboBox jComboBoxTaskType;
    private javax.swing.JFormattedTextField jFormattedTextFieldToDoBefore;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPriority;
    private javax.swing.JLabel jLabelToDoBefore;
    private javax.swing.JLabel jLabelWithDesign;
    private javax.swing.JSlider jSliderPriority;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
