//<editor-fold defaultstate="collapsed" desc="Jibberish">
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.*;
import java.util.*;
import connections.MySQL;
import forminterface.ParentFormInterface;
import gui.mysql.ConnectionSettingsFrame;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;
//</editor-fold>
/**
 *
 * @author jeroen
 */
public class MainFrame extends javax.swing.JFrame implements ParentFormInterface {

    //<editor-fold defaultstate="collapsed" desc="Declarations">
    private MySQL connectionSettings;
    ConnectionSettingsFrame connectionSettingsFrame;
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Constructor">
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        loadSettings();
	quickAdd.Initialize(connectionSettings);
    }
    //</editor-fold>
    
    //<editor-fold desc="Functions">
    //<editor-fold defaultstate="collapsed" desc="Load Settings">
    private void loadSettings(){
        File f = new File("ServerSettings.ser");
        if (f.exists()) {
            try {
                FileInputStream file = new FileInputStream("ServerSettings.ser");
                ObjectInputStream stream = new ObjectInputStream(file);
                connectionSettings = (MySQL) stream.readObject();
                stream.close();
                file.close();
                jMenuItemConnect.setEnabled(false);
                jMenuItemDisconnect.setEnabled(true);
            } catch (IOException exception) {
                exception.printStackTrace();
            } catch (ClassNotFoundException exception) {
                System.out.println("Employee class not found");
                exception.printStackTrace();
            }
        }
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Update Settings">
    private void updateSettings(MySQL connectionSettings) {
        this.connectionSettings = connectionSettings;
        if (connectionSettingsFrame != null) {
            connectionSettingsFrame.dispose();
        }
        if (connectionSettings != null) {
            try {
                FileOutputStream fileOut = new FileOutputStream("ServerSettings.ser");
                ObjectOutputStream out = new ObjectOutputStream(fileOut);
                out.writeObject(connectionSettings);
                out.close();
                fileOut.close();
            } catch (IOException i) {
                i.printStackTrace();
            }
            jMenuItemConnect.setEnabled(false);
            jMenuItemDisconnect.setEnabled(true);
        } else {
            File file = new File("ServerSettings.ser");
            file.delete();
            jMenuItemConnect.setEnabled(true);
            jMenuItemDisconnect.setEnabled(false);
        }
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Generated Code">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        quickAdd = new gui.QuickAdd();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuServer = new javax.swing.JMenu();
        jMenuItemConnect = new javax.swing.JMenuItem();
        jMenuItemDisconnect = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jMenuServer.setText("Server");
        jMenuServer.setToolTipText("");

        jMenuItemConnect.setText("Connect");
        jMenuItemConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConnectActionPerformed(evt);
            }
        });
        jMenuServer.add(jMenuItemConnect);

        jMenuItemDisconnect.setText("Disconnect");
        jMenuItemDisconnect.setEnabled(false);
        jMenuItemDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDisconnectActionPerformed(evt);
            }
        });
        jMenuServer.add(jMenuItemDisconnect);

        jMenuBar.add(jMenuServer);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(quickAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(quickAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Menu Item Connect Click">
    private void jMenuItemConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConnectActionPerformed
        connectionSettingsFrame = new gui.mysql.ConnectionSettingsFrame();
        connectionSettingsFrame.setVisible(true);
        connectionSettingsFrame.setParent(this);
    }//GEN-LAST:event_jMenuItemConnectActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Menu Item Disconnect Click">
    private void jMenuItemDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDisconnectActionPerformed
        updateSettings(null);
    }//GEN-LAST:event_jMenuItemDisconnectActionPerformed
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Form Window Opened">
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Generated Code">
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemConnect;
    private javax.swing.JMenuItem jMenuItemDisconnect;
    private javax.swing.JMenu jMenuServer;
    private javax.swing.JScrollPane jScrollPane1;
    private gui.QuickAdd quickAdd;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Update (listener function)">
    @Override
    public void UpdateForm(String function, ArrayList<Object> args) {
        if (function.equals("updateSettings")) {
            MySQL arg = (MySQL) args.get(0);
            updateSettings(arg);
        }
    }
    //</editor-fold>
    //</editor-fold>
}
