/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import connections.MySQL;
import forminterface.ParentFormInterface;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jeroen
 */
public class QuickAdd extends javax.swing.JPanel {

    MySQL connectionSettings;
    ParentFormInterface parent;

    public void setParent(ParentFormInterface parent) {
        this.parent = parent;
    }

    /**
     * Creates new form QuickAdd
     */
    public QuickAdd() {
        initComponents();
    }

    public void Initialize(MySQL connectionSettings, ParentFormInterface parent) {
        setParent(parent);
        if (connectionSettings != null) {
            this.connectionSettings = connectionSettings;
            ArrayList<String> columns = new ArrayList<>();
            columns.add("TaskTypeName");
            ArrayList<String[]> SQLReturn = new ArrayList<>();
            try {
                SQLReturn = connectionSettings.getSQL("SELECT ? FROM TaskType", columns);
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            jComboBoxTaskType.removeAllItems();
            for (String[] entry : SQLReturn) {
                jComboBoxTaskType.addItem(entry[0]);
            }
            setFieldsVisibility();
        }
    }

    private void setFieldsVisibility() {
        switch (jComboBoxTaskType.getSelectedItem().toString()) {
            case "[SELECT]":
                jLabelToDoBefore.setVisible(false);
                jFormattedTextFieldToDoBefore.setVisible(false);
                jLabelPriority.setVisible(false);
                jSliderPriority.setVisible(false);
                break;
            case "ToDo":
                jLabelToDoBefore.setVisible(true);
                jFormattedTextFieldToDoBefore.setVisible(true);
                jLabelPriority.setVisible(true);
                jSliderPriority.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdd = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jComboBoxTaskType = new javax.swing.JComboBox();
        jFormattedTextFieldToDoBefore = new javax.swing.JFormattedTextField();
        jLabelToDoBefore = new javax.swing.JLabel();
        jSliderPriority = new javax.swing.JSlider();
        jLabelPriority = new javax.swing.JLabel();
        jLabelWithDesign = new javax.swing.JLabel();

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabelName.setText("Name");

        jComboBoxTaskType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTaskTypeItemStateChanged(evt);
            }
        });

        jFormattedTextFieldToDoBefore.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yy/M/d"))));
        jFormattedTextFieldToDoBefore.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldToDoBeforeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldToDoBeforeFocusLost(evt);
            }
        });

        jLabelToDoBefore.setText("To Do Before");

        jSliderPriority.setMaximum(5);
        jSliderPriority.setMinimum(1);
        jSliderPriority.setValue(3);

        jLabelPriority.setText("Priority");

        jLabelWithDesign.setText("______________________________________________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWithDesign)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addComponent(jLabelToDoBefore)
                            .addComponent(jLabelPriority))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldToDoBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxTaskType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSliderPriority, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelWithDesign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelToDoBefore)
                                .addGap(32, 32, 32))
                            .addComponent(jLabelPriority)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxTaskType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldToDoBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdd)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTaskTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTaskTypeItemStateChanged
        jFormattedTextFieldToDoBefore.setText(currentDate());
        setFieldsVisibility();
    }//GEN-LAST:event_jComboBoxTaskTypeItemStateChanged

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        ArrayList<String> columns = new ArrayList<>();
        columns.add("ToDoName");
        columns.add("ToDoBefore");
        columns.add("ToDoPriority");
        ArrayList<String> values = new ArrayList<>();
        values.add(jTextFieldName.getText());
        values.add(jFormattedTextFieldToDoBefore.getText());
        values.add(String.valueOf(jSliderPriority.getValue()));
        try {
            connectionSettings.setInsertInto("ToDo", columns, values);
            jTextFieldName.setText("");
            jFormattedTextFieldToDoBefore.setText("");
            jSliderPriority.setValue(3);
            jComboBoxTaskType.setSelectedIndex(0);
        } catch (SQLException ex) {
            Logger.getLogger(QuickAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        parent.UpdateForm("FillToDoList", null);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jFormattedTextFieldToDoBeforeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldToDoBeforeFocusGained
        jFormattedTextFieldToDoBefore.setText("");
    }//GEN-LAST:event_jFormattedTextFieldToDoBeforeFocusGained

    private void jFormattedTextFieldToDoBeforeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldToDoBeforeFocusLost
        // TODO add your handling code here:
        if (jFormattedTextFieldToDoBefore.getText().equals("")) {
            jFormattedTextFieldToDoBefore.setText(currentDate());
        }
    }//GEN-LAST:event_jFormattedTextFieldToDoBeforeFocusLost

    private String currentDate() {
        String returner;
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yy/MM/dd");
        returner = sdf.format(date);
        return returner;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JComboBox jComboBoxTaskType;
    private javax.swing.JFormattedTextField jFormattedTextFieldToDoBefore;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPriority;
    private javax.swing.JLabel jLabelToDoBefore;
    private javax.swing.JLabel jLabelWithDesign;
    private javax.swing.JSlider jSliderPriority;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
